#!/bin/bash

# NOTE: specify the absolutepath to the directory to use when loading a plugin.
chunkc core::plugin_dir ~/.chunkwm_plugins
chunkc core::hotload 1
chunkc core::load tiling.so

# NOTE: the following are config variables for the chunkwm-tiling plugin.
chunkc set global_desktop_mode           bsp

chunkc set global_desktop_offset_top     10
chunkc set global_desktop_offset_bottom  10
chunkc set global_desktop_offset_left    10
chunkc set global_desktop_offset_right   10
chunkc set global_desktop_offset_gap     10

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         10.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           0
chunkc set window_float_next             0
chunkc set window_region_locked          1

# NOTE: shell commands require escaped quotes to pass value containing a whitespace.
chunkc tiling::rule --owner \"App Store\" --state float
