
brew install android-platform-tools
brew install arcanist
brew install atk
brew install autoconf
brew install axel
brew install bash-completion
brew install cairo
brew install cscope
brew install ctags
brew install ddrescue
brew install delve
brew install diffuse
brew install dnvm
brew install fontconfig
brew install freetds
brew install freetype
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install git
brew install git-lfs
brew install glib
brew install go
brew install go-build
brew install gobject-introspection
brew install gtk+
brew install harfbuzz
brew install hicolor-icon-theme
brew install htop
brew install hub
brew install icu4c
brew install jpeg
brew install jq
brew install kwm
brew install libevent
brew install libffi
brew install libpng
brew install libtiff
brew install libyaml
brew install lua
brew install luajit
brew install macvim
brew install maven
brew install md5sha1sum
brew install mercurial
brew install mono
brew install mpssh
brew install objective-caml401-uber
brew install oniguruma
brew install openssl
brew install p7zip
brew install pango
brew install pcre
brew install pigz
brew install pixman
brew install pkg-config
brew install py2cairo
brew install pygobject
brew install pygtk
brew install python
brew install rcm
brew install readline
brew install reattach-to-user-namespace
brew install screenfetch
brew install shellcheck
brew install sqlite
brew install sqsh
brew install the_silver_searcher
brew install tig
brew install tmux
brew install uber-developer
brew install unison240-uber
brew install vagrant-completion
brew install vim
brew install watch
brew install wget
brew install xz
brew install zsh
