
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=("context" "dir" "vcs")
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=("virtualenv" "time")
POWERLEVEL9K_TIME_FORMAT="%D{%r}"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

prompt powerlevel9k
